_BASE_: "./CLIP_fast_rcnn_R_50_C4.yaml"
MODEL:
  MASK_ON: False
  PROPOSAL_GENERATOR:
    NAME: 'GroundingDino'
  ROI_HEADS:
    NUM_CLASSES: 1203
    NMS_THRESH_TEST: 0.5
  CLIP:
    NO_BOX_DELTA: True
    OFFLINE_RPN_NMS_THRESH: 0.9
repo_type: "IDEA-Research/grounding-dino-tiny"